In [47]:
import matplotlib.pyplot as plt
import numpy as np
np.set_printoptions(precision=2, suppress=True)
%matplotlib inline


def get_eigs(T):
    T = np.array(T)
    eigvals, eigvecs = np.linalg.eig(T)

    # We want to normalize the eigenvectors - make them sum to 1.
    # So, sum down the columns, then divide each column by its sum
    col_sums = eigvecs.sum(axis=0, keepdims=True)

    # Problem - some of those columns sum could be 0.  We can't divide by 0.  So, we protect ourselves by:
    # Finds columns sums that are close to 0
    tol = 0.001
    idx = np.abs(col_sums) < tol
    # Now put 1 in each of those spots.  When you divide by 1, nothing happens.
    #So, a column that sums to 0 will have nothing done to it.
    col_sums[idx] = 1
    eigvecs = eigvecs / col_sums
    return eigvals, eigvecs

In [48]:
# Mars colonies

T = [[0.65, 0.00, 0.30],
     [0.20, 0.90, 0.00],
     [0.15, 0.10, 0.70]
    ]

T = np.array(T)
n = len(T)   # Detect number of states

eigvals, eigvecs = get_eigs(T)

print(eigvals)
i = 0
val = eigvals[i]
good_vec = eigvecs[:,i]
print("Eigen analysis says stationary distribution should be")
print(good_vec)

print("\n Let run it and check")
# Inital distribution is arbitrary.  Here are two commonly used ones.  

# This starts everyone at state k
k = 3
k = min(k, n-1)  # States are 0, 1, 2, ..., n-1.  If you pick k > n-1, this fixes your error.
x = np.zeros(n)
x[k] = 1.0

# This makes it uniform across all states.
# x = np.ones(n)/n

print(x)
x_result = [x]
Steps = 100

for i in range(Steps):
    x = T.dot(x)
    x_result.append(x)
    
x_result = np.array(x_result)
print(x_result)
print("Eigen analysis says it should be")
print(good_vec)
print("Do they match?")

[ 1.    0.5   0.75]
Eigen analysis says stationary distribution should be
[ 0.24  0.48  0.28]

 Let run it and check
[ 0.  0.  1.]
[[ 0.    0.    1.  ]
 [ 0.3   0.    0.7 ]
 [ 0.41  0.06  0.53]
 [ 0.42  0.14  0.44]
 [ 0.41  0.21  0.39]
 [ 0.38  0.27  0.35]
 [ 0.35  0.32  0.33]
 [ 0.33  0.36  0.32]
 [ 0.31  0.39  0.31]
 [ 0.29  0.41  0.3 ]
 [ 0.28  0.43  0.29]
 [ 0.27  0.44  0.29]
 [ 0.26  0.45  0.29]
 [ 0.26  0.46  0.29]
 [ 0.25  0.46  0.28]
 [ 0.25  0.47  0.28]
 [ 0.25  0.47  0.28]
 [ 0.25  0.47  0.28]
 [ 0.24  0.47  0.28]
 [ 0.24  0.48  0.28]
 [ 0.24  0.48  0.28]
 [ 0.24  0.48  0.28]
 [ 0.24  0.48  0.28]
 [ 0.24  0.48  0.28]
 [ 0.24  0.48  0.28]
 [ 0.24  0.48  0.28]
 [ 0.24  0.48  0.28]
 [ 0.24  0.48  0.28]
 [ 0.24  0.48  0.28]
 [ 0.24  0.48  0.28]
 [ 0.24  0.48  0.28]
 [ 0.24  0.48  0.28]
 [ 0.24  0.48  0.28]
 [ 0.24  0.48  0.28]
 [ 0.24  0.48  0.28]
 [ 0.24  0.48  0.28]
 [ 0.24  0.48  0.28]
 [ 0.24  0.48  0.28]
 [ 0.24  0.48  0.28]
 [ 0.24  0.48  0.28]
 [ 0.24  0.48  0.28]
 [ 0.24 

In [43]:
# Growing shrub

r = 7
T = [[1, 1],
     [r, 0],
    ]

T = np.array(T)
n = len(T)   # Detect number of states

eigvals, eigvecs = get_eigs(T)

print(eigvals)
i = 0
val = eigvals[i]
good_vec = eigvecs[:,i]
print("Eigen analysis says stationary distribution should be")
print(good_vec)

print("\n Let run it and check")
print("Start with 0 mature and 1 young branch.")
x = np.array([0,1.0])
print(x)
x_result = [x]
Steps = 100

for i in range(Steps):
    x = T.dot(x)
    x_result.append(x)
x_result = np.array(x_result)
# print(x_result)
row_sums = x_result.sum(axis=1, keepdims=True)
x_result_normalized = x_result / row_sums
print(x_result_normalized)
print("Eigen analysis says it should be")
print(good_vec)
print("Do they match?")

[ 3.19 -2.19]
Eigen analysis says stationary distribution should be
[ 0.31  0.69]

 Let run it and check
Start with 1 young branch, 0 mature
[ 0.  1.]
[[ 0.    1.  ]
 [ 1.    0.  ]
 [ 0.12  0.88]
 [ 0.53  0.47]
 [ 0.21  0.79]
 [ 0.4   0.6 ]
 [ 0.26  0.74]
 [ 0.35  0.65]
 [ 0.29  0.71]
 [ 0.33  0.67]
 [ 0.3   0.7 ]
 [ 0.32  0.68]
 [ 0.31  0.69]
 [ 0.32  0.68]
 [ 0.31  0.69]
 [ 0.32  0.68]
 [ 0.31  0.69]
 [ 0.31  0.69]
 [ 0.31  0.69]
 [ 0.31  0.69]
 [ 0.31  0.69]
 [ 0.31  0.69]
 [ 0.31  0.69]
 [ 0.31  0.69]
 [ 0.31  0.69]
 [ 0.31  0.69]
 [ 0.31  0.69]
 [ 0.31  0.69]
 [ 0.31  0.69]
 [ 0.31  0.69]
 [ 0.31  0.69]
 [ 0.31  0.69]
 [ 0.31  0.69]
 [ 0.31  0.69]
 [ 0.31  0.69]
 [ 0.31  0.69]
 [ 0.31  0.69]
 [ 0.31  0.69]
 [ 0.31  0.69]
 [ 0.31  0.69]
 [ 0.31  0.69]
 [ 0.31  0.69]
 [ 0.31  0.69]
 [ 0.31  0.69]
 [ 0.31  0.69]
 [ 0.31  0.69]
 [ 0.31  0.69]
 [ 0.31  0.69]
 [ 0.31  0.69]
 [ 0.31  0.69]
 [ 0.31  0.69]
 [ 0.31  0.69]
 [ 0.31  0.69]
 [ 0.31  0.69]
 [ 0.31  0.69]
 [ 0.31  0.69]
 [ 0.31  

In [45]:
# Naive Google PageRank

# I find it easier to enter the matrix correctly if put all OUT arrows for state i into ROW i.
# But that should be COLUMN i.  So, we do the tranpose.

adj = [[0, 0, 1, 1, 1, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 1]
      ]
A = np.array(adj)
A = A.T
col_sums = A.sum(axis=0, keepdims=True)
T = A / col_sums
print(T)
n = len(T)   # Detect number of states


eigvals, eigvecs = get_eigs(T)

print(eigvals)
i = 0
val = eigvals[i]
good_vec = eigvecs[:,i]
print("Eigen analysis says stationary distribution should be")
print(good_vec)

print("\n Let run it and check")
# This makes it even across all states.
x = np.ones(n)/n

print(x)
x_result = [x]
Steps = 100

for i in range(Steps):
    x = T.dot(x)
    x_result.append(x)
x_result = np.array(x_result)
row_sums = x_result.sum(axis=1, keepdims=True)
x_result_normalized = x_result / row_sums
print(x_result_normalized)
print("Eigen analysis says it should be")
print(good_vec)
print("Do they match?")

[[ 0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.  ]
 [ 0.33  1.    0.    1.    0.    0.  ]
 [ 0.33  0.    1.    0.    0.5   0.  ]
 [ 0.33  0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.5   1.  ]]
[ 1. -1.  1.  0.  0.  0.]
Eigen analysis says stationary distribution should be
[ 0.   0.   0.5  0.5  0.   0. ]

 Let run it and check
[ 0.17  0.17  0.17  0.17  0.17  0.17]
[[ 0.17  0.17  0.17  0.17  0.17  0.17]
 [ 0.    0.    0.39  0.31  0.06  0.25]
 [ 0.    0.    0.31  0.42  0.    0.28]
 [ 0.    0.    0.42  0.31  0.    0.28]
 [ 0.    0.    0.31  0.42  0.    0.28]
 [ 0.    0.    0.42  0.31  0.    0.28]
 [ 0.    0.    0.31  0.42  0.    0.28]
 [ 0.    0.    0.42  0.31  0.    0.28]
 [ 0.    0.    0.31  0.42  0.    0.28]
 [ 0.    0.    0.42  0.31  0.    0.28]
 [ 0.    0.    0.31  0.42  0.    0.28]
 [ 0.    0.    0.42  0.31  0.    0.28]
 [ 0.    0.    0.31  0.42  0.    0.28]
 [ 0.    0.    0.42  0.31  0.    0.28]
 [ 0.    0.    0.31  0.42  0.    0.28]
 [ 0.  

It does *not* work this time.  The eigen analysis said states 2 & 3 should be the equal and all others should be 0.  That's not what we got.

You can see why.  State 5 is an "absorbing" state - if you get there, you can never leave.  States 2 & 3 bounce back and forth.

Now, Page and Brin avoided these problems by introducing a correction - a small chance that a user "jumps" at random to any state, whether there is a link or not.  Below, we'll repeat that.  But, still, we should be bothered that the eigen analysis seems to have lied when used for the Naive PageRank.  We'll come back to this.

In [46]:
# Wise Google PageRank

# I find it easier to enter the matrix correctly if put all OUT arrows for state i into ROW i.
# But that should be COLUMN i.  So, we do the tranpose.

adj = [[0, 0, 1, 1, 1, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 1]
      ]
A = np.array(adj)
A = A.T
col_sums = A.sum(axis=0, keepdims=True)
T = A / col_sums
n = len(T)   # Detect number of states
p = 0.9
q = 1 - p
T = T*p + q/n

print(T)

eigvals, eigvecs = get_eigs(T)

print(eigvals)
i = 1
val = eigvals[i]
good_vec = eigvecs[:,i]
print("Eigen analysis says stationary distribution should be")
print(good_vec)

print("\n Let run it and check")
# This makes it even across all states.
x = np.ones(n)/n

print(x)
x_result = [x]
Steps = 100

for i in range(Steps):
    x = T.dot(x)
    x_result.append(x)
x_result = np.array(x_result)
row_sums = x_result.sum(axis=1, keepdims=True)
x_result_normalized = x_result / row_sums
print(x_result_normalized)
print("Eigen analysis says it should be")
print(good_vec)
print("Do they match?")

[[ 0.02  0.02  0.02  0.02  0.02  0.02]
 [ 0.02  0.02  0.02  0.02  0.02  0.02]
 [ 0.32  0.92  0.02  0.92  0.02  0.02]
 [ 0.32  0.02  0.92  0.02  0.47  0.02]
 [ 0.32  0.02  0.02  0.02  0.02  0.02]
 [ 0.02  0.02  0.02  0.02  0.47  0.92]]
[-0.9  1.   0.9  0.  -0.   0. ]
Eigen analysis says stationary distribution should be
[ 0.02  0.02  0.34  0.34  0.02  0.26]

 Let run it and check
[ 0.17  0.17  0.17  0.17  0.17  0.17]
[[ 0.17  0.17  0.17  0.17  0.17  0.17]
 [ 0.02  0.02  0.37  0.29  0.07  0.24]
 [ 0.02  0.02  0.3   0.38  0.02  0.26]
 [ 0.02  0.02  0.38  0.3   0.02  0.26]
 [ 0.02  0.02  0.31  0.37  0.02  0.26]
 [ 0.02  0.02  0.37  0.31  0.02  0.26]
 [ 0.02  0.02  0.31  0.37  0.02  0.26]
 [ 0.02  0.02  0.37  0.31  0.02  0.26]
 [ 0.02  0.02  0.32  0.36  0.02  0.26]
 [ 0.02  0.02  0.36  0.32  0.02  0.26]
 [ 0.02  0.02  0.32  0.36  0.02  0.26]
 [ 0.02  0.02  0.36  0.32  0.02  0.26]
 [ 0.02  0.02  0.33  0.35  0.02  0.26]
 [ 0.02  0.02  0.36  0.33  0.02  0.26]
 [ 0.02  0.02  0.33  0.35  0.02  0

Now, let's go back to Naive PageRank and try to understand what went wrong with the eigen analysis.

In [10]:
# Naive Google PageRank


# I find it easier to enter the matrix correctly if put all OUT arrows for state i into ROW i.
# But that should be COLUMN i.  So, we do the tranpose.

adj = [[0, 0, 1, 1, 1, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 1]
      ]
A = np.array(adj)
A = A.T
col_sums = A.sum(axis=0, keepdims=True)
T = A / col_sums
print(T)
n = len(T)   # Detect number of states

eigvals, eigvecs = get_eigs(T)
print(eigvals)

[[ 0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.  ]
 [ 0.33  1.    0.    1.    0.    0.  ]
 [ 0.33  0.    1.    0.    0.5   0.  ]
 [ 0.33  0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.5   1.  ]]
[ 1. -1.  1.  0.  0.  0.]


The issue is that there are THREE eigenvalues tied for largest (we take the absolute value).

In [11]:
i = [0,1,2]
val = eigvals[i]
vec = eigvecs[:,i]  #recall, eigenvectors go DOWN columns, not across rows
print(vec)
print()
print(T.dot(vec))
print()
print(T.dot(T.dot(vec)))

[[ 0.    0.    0.  ]
 [ 0.    0.    0.  ]
 [ 0.5   0.71  0.  ]
 [ 0.5  -0.71  0.  ]
 [ 0.    0.    0.  ]
 [ 0.    0.    1.  ]]

[[ 0.    0.    0.  ]
 [ 0.    0.    0.  ]
 [ 0.5  -0.71  0.  ]
 [ 0.5   0.71  0.  ]
 [ 0.    0.    0.  ]
 [ 0.    0.    1.  ]]

[[ 0.    0.    0.  ]
 [ 0.    0.    0.  ]
 [ 0.5   0.71  0.  ]
 [ 0.5  -0.71  0.  ]
 [ 0.    0.    0.  ]
 [ 0.    0.    1.  ]]


Note that columns 0 and 2 do not change - they have eigenvalue +1.  
Column 0 says "System is stable if states 2 & 3 are equal and all others are 0."
Column 2 says "System is stable if state 5 is 1 (everyone) and all others are 0."

But column 1 DOES change - the negative changes position.  Then it changes back on the next step.  This is because it has eigenvalue -1.

Column 1 says "System stably bounces back and forth between...
  - "Everyone at state 2"
  - "Everyone at state 3"

In [14]:
print("\n Let run it and check")

# Inital distribution MATTERS

def run_trial(x):
    x = np.array(x)
    x_result = [x]
    Steps = 100

    for i in range(Steps):
        x = T.dot(x)
        x_result.append(x)
    x_result = np.array(x_result)
    row_sums = x_result.sum(axis=1, keepdims=True)
    x_result_normalized = x_result / row_sums
    print(x_result_normalized)

print("Run with initial distribution = column 0")
x = [0, 0, 0.5, 0.5, 0, 0]
run_trial(x)
print("Eigen analysis says it should be")
print(eigvecs[:,0])
print("Do they match?")


print()
print("Run with initial distribution = column 2")
x = [0, 0, 0, 0, 0, 1.0]
run_trial(x)
print("Eigen analysis says it should be")
print(eigvecs[:,2])
print("Do they match?")


print()
print("Run with initial distribution = everyone at 2")
x = [0, 0, 1.0, 0, 0, 0.0]
run_trial(x)
print("Eigen analysis says it should oscilate between states 2 & 3")
print("Do they match?")




 Let run it and check
Run with initial distribution = column 0
[[ 0.   0.   0.5  0.5  0.   0. ]
 [ 0.   0.   0.5  0.5  0.   0. ]
 [ 0.   0.   0.5  0.5  0.   0. ]
 [ 0.   0.   0.5  0.5  0.   0. ]
 [ 0.   0.   0.5  0.5  0.   0. ]
 [ 0.   0.   0.5  0.5  0.   0. ]
 [ 0.   0.   0.5  0.5  0.   0. ]
 [ 0.   0.   0.5  0.5  0.   0. ]
 [ 0.   0.   0.5  0.5  0.   0. ]
 [ 0.   0.   0.5  0.5  0.   0. ]
 [ 0.   0.   0.5  0.5  0.   0. ]
 [ 0.   0.   0.5  0.5  0.   0. ]
 [ 0.   0.   0.5  0.5  0.   0. ]
 [ 0.   0.   0.5  0.5  0.   0. ]
 [ 0.   0.   0.5  0.5  0.   0. ]
 [ 0.   0.   0.5  0.5  0.   0. ]
 [ 0.   0.   0.5  0.5  0.   0. ]
 [ 0.   0.   0.5  0.5  0.   0. ]
 [ 0.   0.   0.5  0.5  0.   0. ]
 [ 0.   0.   0.5  0.5  0.   0. ]
 [ 0.   0.   0.5  0.5  0.   0. ]
 [ 0.   0.   0.5  0.5  0.   0. ]
 [ 0.   0.   0.5  0.5  0.   0. ]
 [ 0.   0.   0.5  0.5  0.   0. ]
 [ 0.   0.   0.5  0.5  0.   0. ]
 [ 0.   0.   0.5  0.5  0.   0. ]
 [ 0.   0.   0.5  0.5  0.   0. ]
 [ 0.   0.   0.5  0.5  0.   0. ]
 [ 0.   0.  

In [26]:
# Kai-Quinten Bunk Bed Hopping

import matplotlib.pyplot as plt
import numpy as np
np.set_printoptions(precision=2, suppress=True)
%matplotlib inline

# state = [where Kai sleeps tonight, where Quinten sleeps tonight]

# state 0 = [bottom, bottom]
# state 1 = [top, bottom]
# state 2 = [top, top]
# state 3 = [bottom, top]

# I find it easier to enter the matrix correctly if put all OUT arrows for state i into ROW i.
# But that should be COLUMN i.  So, we do the tranpose.

adj = [[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
      ]
A = np.array(adj)
A = A.T
col_sums = A.sum(axis=0, keepdims=True)
T = A / col_sums
n = len(T)   # Detect number of states

print(T)

eigvals, eigvecs = get_eigs(T)

print(eigvals)
i = 3
val = eigvals[i]
good_vec = eigvecs[:,i]
print("Eigen analysis says stationary distribution should be")
print(good_vec)

print("\n Let run it and check")
print("Let's start with [bottom, bottom]")
print(x)
x_result = [x]
Steps = 100

for i in range(Steps):
    x = T.dot(x)
    x_result.append(x)
x_result = np.array(x_result)
row_sums = x_result.sum(axis=1, keepdims=True)
x_result_normalized = x_result / row_sums
print(x_result_normalized)
print("Eigen analysis says it should be")
print(good_vec)
print("Do they match?")

[[ 0.  0.  0.  1.]
 [ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]]
[-1.+0.j  0.+1.j  0.-1.j  1.+0.j]
Eigen analysis says stationary distribution should be
[ 0.25-0.j  0.25-0.j  0.25-0.j  0.25-0.j]

 Let run it and check
[ 0.25  0.25  0.25  0.25]
[[ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  

In [27]:
print("\n Let run it and check")

# Inital distribution MATTERS

def run_trial(x):
    x = np.array(x)
    x_result = [x]
    Steps = 100

    for i in range(Steps):
        x = T.dot(x)
        x_result.append(x)
    x_result = np.array(x_result)
    row_sums = x_result.sum(axis=1, keepdims=True)
    x_result_normalized = x_result / row_sums
    print(x_result_normalized)

print("Run with uniform distribution")
x = [1/4, 1/4, 1/4, 1/4]
run_trial(x)
print("Eigen analysis says it should be")
print(eigvecs[:,3])
print("Do they match?")


print()
print("Run with initial distribution all on state 0")
x = [1, 0, 0, 0]
run_trial(x)
print("Eigen analysis says it should cycle among the 4 states.  It has period = 4")
print("Do they match?")


print()
print("Run with initial distribution equally on states 0 and 2")
x = [1/2, 0, 1/2, 0]
run_trial(x)
print("Eigen analysis says it should cycle among (0,2) and (1,3).  It has period = 2")
print("Do they match?")


print()
print("Run with initial distribution equally on 0, 1, 2")
x = [1/3, 1/3, 1/3, 0]
run_trial(x)
print("Eigen analysis says it should cycle where 1 state is empty, rest are equal.  It has period = 4")
print("Do they match?")


 Let run it and check
Run with uniform distribution
[[ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [ 0.25  0.25  0.25  0.25]
 [

How to detect the period from the eigenvalue?  Raise to higher and higher power until you get 1.

In [39]:
print("Analyze 1st eigval")
v = eigvals[0]
print(v)
print("Nope, that's -1.  We want +1")
print(v**2)
print("Done.  There is a stable oscillation with period 2")

print()
print("Analyze 2nd eigval")
v = eigvals[1]
print(v)
print("Nope, that's +i.  We want +1")
print(v**2)
print("Nope, that's -1.  We want +1)")
print(v**3)
print("Nope, that's -i.  We want +1")
print(v**4)
print("Done.  There is a stable oscillation with period 4")

print()
print("Analyze 3rd eigval")
v = eigvals[2]
print(v)
print("Nope, that's -i.  We want +1")
print(v**2)
print("Nope, that's -1.  We want +1)")
print(v**3)
print("Nope, that's +i.  We want +1")
print(v**4)
print("Done.  There is another stable oscillation with period 4")

print()
print("Analyze 4th eigval")
v = eigvals[3]
print(v)
print("Done.  There is a stable oscillation with period 1 ... equilibrium.")

Analyze 1st eigval
(-1+0j)
Nope, that's -1.  We want +1
(1-0j)
Done.  There is a stable oscillation with period 2

Analyze 2nd eigval
(8.32667268469e-17+1j)
Nope, that's +i.  We want +1
(-1+1.66533453694e-16j)
Nope, that's -1.  We want +1)
(-2.49800180541e-16-1j)
Nope, that's -i.  We want +1
(1-3.33066907388e-16j)
Done.  There is a stable oscillation with period 4

Analyze 3rd eigval
(8.32667268469e-17-1j)
Nope, that's -i.  We want +1
(-1-1.66533453694e-16j)
Nope, that's -1.  We want +1)
(-2.49800180541e-16+1j)
Nope, that's +i.  We want +1
(1+3.33066907388e-16j)
Done.  There is another stable oscillation with period 4

Analyze 4th eigval
(1+0j)
Done.  There is a stable oscillation with period 1 ... equilibrium.
